name: Dependent Jobs Example
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./setup_server.sh
  build1:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./build_server.sh
  build2:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./build_server.sh
  test:
    needs: [build1, build2]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flag: [6, 8, 10]
    steps:
      - uses: actions/checkout@v2
      - name: Testing Step 
        run: ./test_server.sh
        env:
          THE_FLAG: ${{ matrix.flag }}
